# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

kind-dependencies:
    - toolchain
    - build

job-defaults:
    attributes:
        build-type: debug
        code-review: true
        retrigger: true
    dependencies:
        build-debug: build-focus-debug
        build-android-test: build-android-test-debug
    fetches:
        toolchain:
            - android-sdk-linux
            - android-gradle-dependencies
    worker-type: b-android
    worker:
        docker-image: {in-tree: ui-tests}
        max-run-time: 7200
        env:
            GOOGLE_APPLICATION_CREDENTIALS: '.firebase_token.json'
            GOOGLE_PROJECT: 'moz-fx-mobile-firebase-testlab'
        artifacts:
            - name: public
              path: /builds/worker/artifacts
              type: directory
    run-on-tasks-for: [github-pull-request, github-push]
    treeherder:
        kind: test
        platform: 'ui-test/opt'
        tier: 2
    run:
        use-caches: false
        using: run-commands
        dummy-secrets:
            - content: "faketoken"
              path: .adjust_token
        secrets:
            - name: project/focus/firebase
              key: "keyFile"
              path: .firebase_token.json
              decode: true
        commands:
            - [wget, {artifact-reference: '<build-debug/public/build/app-focus-x86-debug.apk>'}, '-O', app.apk]
            - [wget, {artifact-reference: '<build-android-test/public/build/app-focus-debug-androidTest.apk>'}, '-O', android-test.apk]

jobs:
    x86-debug:
        description: 'UI tests with firebase'
        run:
            commands: 
                - [automation/taskcluster/androidTest/ui-test.sh, x86, app.apk, android-test.apk, '-1']
        treeherder:
            symbol: debug(ui-test-x86)